/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectozombie.interfaz;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import proyectozombie.CharacterCreation.CharacterGame;
import proyectozombie.Users.User;

/**
 *
 * @author Usuario
 */
public class asignarPosicion extends javax.swing.JFrame {
    public ArrayList<CharacterGame> listaEscojida;
    public User usuario;
    /**
     * Creates new form asignarPosicion
     */
    public asignarPosicion(ArrayList<CharacterGame> lista, User usuario) {
        initComponents();
        this.listaEscojida = lista;
        this.usuario = usuario;
        generarComboBoxCharacters();
    }

    private void generarComboBoxCharacters(){
        for(int i=0; i<this.listaEscojida.size(); i++){
            cmbCharacterGame.addItem(this.listaEscojida.get(i).getcName());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cmbCharacterGame = new javax.swing.JComboBox<>();
        btnAsigPos = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        txtFPosicionX = new javax.swing.JTextField();
        lblPosicionY = new javax.swing.JLabel();
        lblPosicionX = new javax.swing.JLabel();
        txtFPosicionY = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(112, 136, 140));

        cmbCharacterGame.setBackground(new java.awt.Color(0, 102, 102));
        cmbCharacterGame.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        cmbCharacterGame.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnAsigPos.setBackground(new java.awt.Color(0, 102, 102));
        btnAsigPos.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnAsigPos.setText("Asignar posicion");
        btnAsigPos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsigPosActionPerformed(evt);
            }
        });

        btnSiguiente.setBackground(new java.awt.Color(149, 175, 174));
        btnSiguiente.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnSiguiente.setForeground(new java.awt.Color(51, 51, 51));
        btnSiguiente.setText("Siguiente");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        lblPosicionY.setText("Posicion en Y");

        lblPosicionX.setText("Posicion en X");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblPosicionY, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSiguiente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbCharacterGame, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAsigPos, javax.swing.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE)
                    .addComponent(txtFPosicionX)
                    .addComponent(lblPosicionX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtFPosicionY))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(cmbCharacterGame, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lblPosicionX, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFPosicionX, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPosicionY, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFPosicionY, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(btnAsigPos, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        campoBatalla_Juego frame = new campoBatalla_Juego(listaEscojida,usuario);
        frame.setDefaultCloseOperation(EXIT_ON_CLOSE);
        frame.pack();
        frame.setLocation(290, 150);
        frame.setVisible(true);
        
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnAsigPosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsigPosActionPerformed
        // TODO add your handling code here:
        int x = Integer.parseInt(txtFPosicionX.getText());
        int y = Integer.parseInt(txtFPosicionY.getText());
        CharacterGame selected = listaEscojida.get(cmbCharacterGame.getSelectedIndex());
        selected.setPosition(x, y);
        JOptionPane.showMessageDialog(jPanel1,"Se ingreso correctamente la posicion para el personaje: " + selected.getcName() + " X: " + x +" Y: " + y 
                ,"Datos ingresados",JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_btnAsigPosActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsigPos;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JComboBox<String> cmbCharacterGame;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblPosicionX;
    private javax.swing.JLabel lblPosicionY;
    private javax.swing.JTextField txtFPosicionX;
    private javax.swing.JTextField txtFPosicionY;
    // End of variables declaration//GEN-END:variables
}
