/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectozombie.interfaz;

import java.awt.Image;
import java.io.File;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import proyectozombie.CharacterCreation.CharacterGame;
import proyectozombie.Logica.FileManager;
import proyectozombie.Users.User;

/**
 *
 * @author monic
 */
public class escogerPartida_Juego extends javax.swing.JFrame {
    User usuario;
    ArrayList<CharacterGame> listaPersonajes;
    /**
     * Creates new form escogerPartida_Juego
     */
    public escogerPartida_Juego(User nuevo) {
        this.usuario=nuevo;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_rutaA = new javax.swing.JLabel();
        btn_EscogidaP = new javax.swing.JButton();
        btn_EscogerP = new javax.swing.JButton();
        lbl_Instruccion = new javax.swing.JLabel();
        lbl_Titulo0 = new javax.swing.JLabel();
        btn_NuevaP = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(null);

        lbl_rutaA.setBackground(new java.awt.Color(0, 0, 0));
        lbl_rutaA.setFont(new java.awt.Font("VCR OSD Mono", 0, 24)); // NOI18N
        lbl_rutaA.setForeground(new java.awt.Color(102, 0, 102));
        lbl_rutaA.setText("Ruta archivo juego");
        lbl_rutaA.setOpaque(true);
        jPanel1.add(lbl_rutaA);
        lbl_rutaA.setBounds(120, 208, 490, 30);

        btn_EscogidaP.setBackground(new java.awt.Color(0, 0, 0));
        btn_EscogidaP.setFont(new java.awt.Font("VCR OSD Mono", 0, 18)); // NOI18N
        btn_EscogidaP.setForeground(new java.awt.Color(102, 0, 102));
        btn_EscogidaP.setText("Escoger partida");
        btn_EscogidaP.setName("Inicio sesión"); // NOI18N
        btn_EscogidaP.setOpaque(false);
        btn_EscogidaP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EscogidaPActionPerformed(evt);
            }
        });
        jPanel1.add(btn_EscogidaP);
        btn_EscogidaP.setBounds(130, 370, 250, 60);

        btn_EscogerP.setBackground(new java.awt.Color(0, 0, 0));
        btn_EscogerP.setFont(new java.awt.Font("VCR OSD Mono", 0, 18)); // NOI18N
        btn_EscogerP.setForeground(new java.awt.Color(102, 0, 102));
        btn_EscogerP.setText("Escoger archivo");
        btn_EscogerP.setName("Inicio sesión"); // NOI18N
        btn_EscogerP.setOpaque(false);
        btn_EscogerP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EscogerPActionPerformed(evt);
            }
        });
        jPanel1.add(btn_EscogerP);
        btn_EscogerP.setBounds(270, 260, 210, 40);

        lbl_Instruccion.setBackground(new java.awt.Color(0, 0, 0));
        lbl_Instruccion.setFont(new java.awt.Font("VCR OSD Mono", 0, 48)); // NOI18N
        lbl_Instruccion.setForeground(new java.awt.Color(102, 0, 102));
        lbl_Instruccion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Instruccion.setText("Herencia al trono");
        lbl_Instruccion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 102)));
        lbl_Instruccion.setOpaque(true);
        jPanel1.add(lbl_Instruccion);
        lbl_Instruccion.setBounds(120, 10, 500, 50);

        lbl_Titulo0.setBackground(new java.awt.Color(0, 0, 0));
        lbl_Titulo0.setFont(new java.awt.Font("VCR OSD Mono", 0, 24)); // NOI18N
        lbl_Titulo0.setForeground(new java.awt.Color(102, 0, 102));
        lbl_Titulo0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Titulo0.setText("Escoja el juego que desea jugar:");
        lbl_Titulo0.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 102)));
        lbl_Titulo0.setOpaque(true);
        jPanel1.add(lbl_Titulo0);
        lbl_Titulo0.setBounds(120, 120, 500, 50);

        btn_NuevaP.setBackground(new java.awt.Color(0, 0, 0));
        btn_NuevaP.setFont(new java.awt.Font("VCR OSD Mono", 0, 18)); // NOI18N
        btn_NuevaP.setForeground(new java.awt.Color(102, 0, 102));
        btn_NuevaP.setText("Nueva partida");
        btn_NuevaP.setName("Inicio sesión"); // NOI18N
        btn_NuevaP.setOpaque(false);
        btn_NuevaP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NuevaPActionPerformed(evt);
            }
        });
        jPanel1.add(btn_NuevaP);
        btn_NuevaP.setBounds(430, 370, 270, 60);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 755, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_EscogerPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EscogerPActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
            "Juegos serializados", "juego");
        chooser.setFileFilter(filter);

        int returnVal = chooser.showOpenDialog(this);
        if(returnVal == JFileChooser.APPROVE_OPTION) {
            lbl_rutaA.setText(chooser.getSelectedFile().getAbsolutePath());
            File selectedFile = chooser.getSelectedFile();
            String selectedImagePath = selectedFile.getAbsolutePath();
            JOptionPane.showMessageDialog(null, selectedImagePath);
        }

    }//GEN-LAST:event_btn_EscogerPActionPerformed

    private void btn_EscogidaPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EscogidaPActionPerformed
        // TODO add your handling code here:
       String ruta = lbl_rutaA.getText();
       usuario = (User) FileManager.readObject(ruta);
       listaPersonajes = usuario.getWarriors();
       this.setVisible(false);
       campoBatalla_Juego frame = new campoBatalla_Juego(listaPersonajes, usuario);
       frame.setDefaultCloseOperation(EXIT_ON_CLOSE);
       frame.pack();
       frame.setLocation(290, 50);
       frame.setVisible(true);
       
    }//GEN-LAST:event_btn_EscogidaPActionPerformed

    private void btn_NuevaPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NuevaPActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        escogerPersonajes_Juego frame = new escogerPersonajes_Juego(usuario);
        frame.setDefaultCloseOperation(EXIT_ON_CLOSE);
        frame.pack();
        frame.setLocation(290, 150);
        frame.setVisible(true);
    }//GEN-LAST:event_btn_NuevaPActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_EscogerP;
    private javax.swing.JButton btn_EscogidaP;
    private javax.swing.JButton btn_NuevaP;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_Instruccion;
    private javax.swing.JLabel lbl_Titulo0;
    private javax.swing.JLabel lbl_rutaA;
    // End of variables declaration//GEN-END:variables
}
